### ISSUE TITLE
Make fails

### ISSUE THREAD

**Issue by lhirlimann** [SamsungInternet/webthings-webapp#6]
git clone
make 
[snip]
mkdir -p "sandbox/rzr/pwa/master"
git clone -b "sandbox/rzr/pwa/master" "https://github.com/samsunginternet/webthings-webapp" "sandbox/rzr/pwa/master"
Cloning into 'sandbox/rzr/pwa/master'...
fatal: Remote branch sandbox/rzr/pwa/master not found in upstream origin
make: *** [Makefile:33: sandbox/rzr/pwa/master] Error 128

**Comment by rzr** [comment]
Sorry for that, let me push it too:
https://github.com/SamsungInternet/webthings-webapp/tree/sandbox/rzr/pwa/master

Is it ok to close now ?

**Comment by lhirlimann** [comment]
Works now .
